C                           DISCLAIMER
C
C   This file was generated by TAMC version 5.3.2
C
C   THE AUTHOR DOES NOT MAKE  ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES
C   ANY LEGAL LIABILITY OR  RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS,
C   OR USEFULNESS  OF ANY INFORMATION OR PROCESS  DISCLOSED, OR REPRESENTS
C   THAT ITS USE WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.
C
C   THIS CODE IS FOR NON-PROFIT-ORIENTED ACADEMIC RESEARCH AND EDUCATION
C   ONLY.  ANY COMMERCIAL OR OTHER PROFIT-ORIENTED USE OR  EVALUATION IS
C   STRICTLY  FORBIDDEN.  PASSING  THIS CODE  TO  ANY THIRD  PARTY IS  NOT
C   ALLOWED.
C
C   FOR COMMERCIAL OR  OTHER PROFIT-ORIENTED APPLICATIONS PLEASE CONTACT
C   info@FastOpt.com
C
      subroutine adpres( u, ires, rpar, ipar, adpdelta, 
     $adpsenpar )
C***************************************************************
C***************************************************************
C** This routine was generated by the                         **
C** Tangent linear and Adjoint Model Compiler,  TAMC 5.3.2    **
C***************************************************************
C***************************************************************
C==============================================
C all entries are defined explicitly
C==============================================
      implicit none

C==============================================
C define arguments
C==============================================
      double precision adpdelta(*)
      double precision adpsenpar(*)
      integer ipar(*)
      integer ires
      double precision rpar(*)
      double precision u(*)

C==============================================
C define local variables
C==============================================
      double precision adptemx
      double precision adptemy
      double precision coeff
      integer i
      integer ioff
      integer j
      integer k
      integer m
      integer m2
      double precision temx
      double precision temy

C----------------------------------------------
C RESET LOCAL ADJOINT VARIABLES
C----------------------------------------------
      adptemx = 0.d0
      adptemy = 0.d0

C----------------------------------------------
C ROUTINE BODY
C----------------------------------------------
      m = ipar(4)
      coeff = rpar(2)
      m2 = m+2
      if (ires .eq. 0) then
        do k = 1, m
          adptemx = 0.d0
          adptemy = 0.d0
          ioff = m2*k
          do j = 1, m
            adptemx = 0.d0
            adptemy = 0.d0
            i = ioff+j+1
            temx = u(i-1)+u(i+1)-2.d0*u(i)
            temy = u(i-m2)+u(i+m2)-2.d0*u(i)
            adptemx = adptemx-adpdelta(i)*coeff
            adptemy = adptemy-adpdelta(i)*coeff
            adpdelta(i) = 0.d0
            adpsenpar(2) = adpsenpar(2)+adptemy*temy
            adptemy = 0.d0
            adpsenpar(1) = adpsenpar(1)+adptemx*temx
            adptemx = 0.d0
          end do
        end do
      endif

      end


